In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
def out(x):
    print(x)
    
out(143.14 / 139.63	)

1.0251378643557973


In [14]:
out(4.33 * (252 )**0.5) 

68.73661906145807


### 熟悉numpy 運算

### delta 

In [9]:
def delta(future_end, future_start, target_end, target_start):
    global target_diff 
    global future_diff 
    target_diff = target_end - target_start
    future_diff = future_end - future_start
    
    if target_diff == 0: 
        raise ZeroDivisionError ( "Cannot divide by zero" ) 
    else : 
        return future_diff / target_diff
    

In [11]:
delta ( 139.63, 143.14, 140.63, 140.62)

-351.0000000003183

In [4]:
a = np.array ([1, 2, 3])
b = np.array ([4, 5, 6])

out (a+ b)


[5 7 9]


In [5]:
a * b

array([ 4, 10, 18])

In [8]:
c = np.array ([1, 2, 3])
c += 1
c

array([2, 3, 4])

In [10]:
lis = [1, 2, 3]
lis += [1]
out(lis)

[1, 2, 3, 1]


In [12]:
lis.append(1)
out(lis)

[1, 2, 3, 1, 1]


In [14]:
d = np.array ([[1, 2, 3], [4, 5, 6]])
d


array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
d.ndim, d.shape

(2, (2, 3))

In [19]:
d[1, -2]



5

In [20]:
d[0, : ]

array([1, 2, 3])

In [21]:
d [0, 1] = 10
d

array([[ 1, 10,  3],
       [ 4,  5,  6]])

In [25]:
e = np.array ([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
e

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
e[0, 1, 2]

6

In [29]:
## 初始化

In [31]:
zero = np.zeros ((2, 3, 3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
zeros = np.zeros((2, 3), dtype = int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
full4 = np.full ((2, 3), 4)
full4

array([[4, 4, 4],
       [4, 4, 4]])

In [39]:
full99 = np.full_like (zero, 99)
# np.full_like: 矩陣大小跟右邊第一個 param size 一樣的 
full99


array([[[99., 99., 99.],
        [99., 99., 99.],
        [99., 99., 99.]],

       [[99., 99., 99.],
        [99., 99., 99.],
        [99., 99., 99.]]])

In [44]:
## np.random.rand ( 小數點 )

random = np.random.rand(2, 3)
random

array([[0.9446032 , 0.89909346, 0.44031408],
       [0.9877645 , 0.52397329, 0.15339148]])

In [45]:
# 有一個shape 我想要初始化成亂數
random_shape = np.random.random_sample (full99.shape)
random_shape

array([[[0.177312  , 0.50117544, 0.06620133],
        [0.86383353, 0.58198417, 0.34202169],
        [0.83905635, 0.64986051, 0.14195628]],

       [[0.31379773, 0.4304982 , 0.3413381 ],
        [0.94295054, 0.33661254, 0.75132611],
        [0.02477789, 0.89980229, 0.57251546]]])

In [54]:
random_int = np.random.randint (4, 7, size = (2, 3)) ## 這邊 4,8 想像成 [4, 8]
random_int


array([[4, 6, 4],
       [5, 6, 4]])

In [65]:
iden = np.identity (3)
for i in range (4):
    iden += iden
iden

array([[16.,  0.,  0.],
       [ 0., 16.,  0.],
       [ 0.,  0., 16.]])

In [58]:
arr = np.array ([[1, 2, 3]])
rep = arr.repeat (3, axis = 0)
rep

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [59]:
repeat = arr.repeat (3, axis = 1)
repeat



array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

### Create a targetted matrix  

In [68]:
full = np.ones((5, 5), dtype = int)
full

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [71]:
z = np.zeros((3, 3), dtype = int)
z[1, 1] = 9
z


array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [72]:
full[1:4, 1:4] = z
full

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [73]:
## be careful 

In [74]:
a = np.array([[1, 2, 3]])
b = a 
b

array([[1, 2, 3]])

In [76]:
b[0, 0] = 100
a

array([[100,   2,   3]])

In [78]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [80]:
d = c.copy()
c[0 ] = 99
d


array([1, 2, 3])

In [81]:
## Math

In [84]:
a = [1, 2, 3]
a += [ 1 ] 
a

[1, 2, 3, 1]

In [95]:
a  = np.array ([1, 2, 3])
a += [ 1 ]
out(a)

a +1 
out(a)







[2 3 4]
[2 3 4]


In [96]:
a * a 

array([ 4,  9, 16])

In [97]:
b = np.array ([0, 1, 2])
a * b


array([0, 3, 8])

In [98]:
## Linear alegebra

In [103]:
a = np.ones ( (2, 3), dtype = int )
out(a)

b = np.full( (3, 2), 2)
out(b)


 


[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [104]:
np.matmul(a , b)

array([[6, 6],
       [6, 6]])

In [105]:
c = np.identity (3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
## Find the determinant
np.linalg.det(c)

1.0

In [109]:
## Stats

In [115]:
a = np.array ([[1, 2, 3], [4, 5, 6]])
a 

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
# total min 
a.min()

1

In [118]:
# axis = 0, row
out(a.min(axis = 0))

# axis = 1. column
out(a.min(axis = 1))

[1 2 3]
[1 4]


In [120]:
# 這種方式也行
np.min(a)

1

In [128]:
a 

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
a.sum() 

21

In [131]:
out(a.sum(axis = 0))
# 沿著 row 加
out(a.sum(axis = 1))
# 沿著 column 加

[5 7 9]
[ 6 15]


In [132]:
a = np.array ([1, 2, 3])
b = np.array ([4, 5, 6])

# vertical stack
vstack = np.vstack((a, b))
out(vstack)

hastack  = np.hstack((a, b))
out(hastack)

            

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [133]:
## indexing 

In [139]:
tot_array = np.array ([[1, 2, 3, 4], [5, 6, 7, 8]])
tot  = tot_array.astype(float)
tot

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [141]:
out(tot>4)
out(tot[tot > 4])

[[False False False False]
 [ True  True  True  True]]
[5. 6. 7. 8.]


In [143]:
a = np.array ([1, 2, 3, 4, 5, 6, 7, 8])
a[[1, 2, -1]]  # 注意這邊是兩層括號

array([2, 3, 8])

In [149]:
## np.any
tot

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [146]:
np.any(tot > 4, axis = 1)

array([False,  True])

In [147]:
np.any(tot> 4, axis = 0)

array([ True,  True,  True,  True])

In [150]:
np.all(tot > 4, axis = 1)

array([False,  True])

In [151]:
np.all(tot>4, axis = 0)

array([False, False, False, False])

In [157]:
(( tot > 4) & (tot < 7 )) 

array([[False, False, False, False],
       [ True,  True, False, False]])

In [158]:
tot

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [156]:
tot [(( tot > 4) & (tot < 7 ))] 

array([5., 6.])

In [161]:
# reverse of the previous
(~(( tot > 4) & (tot < 7 ))).astype(bool)



array([[ True,  True,  True,  True],
       [False, False,  True,  True]])